### ISSUE TITLE
Missing Search Support

### ISSUE THREAD

**Issue by luke-** [humhub/news-issues#1]

**Comment by yurabakhtin** [comment]
@luke- Could you tell me please what search support you mean?
I find only this:

<img width="866" alt="filter" src="https://user-images.githubusercontent.com/6995524/155147237-b9d39775-5bec-4c35-b558-42625df540ff.png">

**Comment by luke-** [comment]
https://docs.humhub.org/docs/develop/search

**Comment by yurabakhtin** [comment]
@luke- Thanks for the info. PR https://github.com/humhub/news/pull/47.

**Comment by luke-** [comment]
@yurabakhtin Thanks!
