### ISSUE TITLE
sidebar widget in dashboard shows posts from spaces without membership

### ISSUE THREAD

**Issue by Dayflare** [humhub/news-issues#2]
i created a post with the news plugin and actived the sidebar widget.
![2022-09-05_09-35](https://user-images.githubusercontent.com/42730126/188411975-d0753339-07b7-454e-b03e-68470c1a00c3.png)

when i login with a user that isn't a member of the spaces where i created the news posts it still shows the news posts in the sidebar widget.
![2022-09-05_11-09](https://user-images.githubusercontent.com/42730126/188412961-082f007d-7f6e-4612-91d4-c12964b05bfb.png)

if i click on the news posts i get an error 
![2022-09-05_09-29](https://user-images.githubusercontent.com/42730126/188412255-4d8278d2-6ce3-4937-bfaa-bd03b163d2b4.png)

The news posts in the sidebar widget should only be shown if the user is member of the space where the post was created. Like the calender widget, where i only see appointments from my spaces in the sidebar widget.

**Comment by luke-** [comment]
Thanks  for the report. Is fixed in module version 1.0.3
