### ISSUE TITLE
news draft visible in dashboard widget

### ISSUE THREAD

**Issue by Dayflare** [humhub/news-issues#3]
after the update 1.1.0 with the draft feature, draft news posts are visible on the dashboard in the news widget for all users. If the user clicks on the draft the draft post is shown to them. I don't know if this is by design but for me users shouldn't be able to see draft posts till they are published.

second problem is after you delete a draft post, the post is still visible in the dashboard widget, only the draft tag gets removed.
If you open the space the post is removed from the news widget.

screenshot from the dashboard widget:
![2023-07-25_11-54](https://github.com/humhub/news-issues/assets/42730126/c9978335-ec75-4910-9d9f-d8655b8fc055)

screenshot from the space widget:
![2023-07-25_11-55](https://github.com/humhub/news-issues/assets/42730126/3ef1c6bb-6bf1-469a-b7ef-51f99af96b49)

If you click on the deleted post in the widget you get redirected to the space in which the post was created.

I hope the screenshots show the error good enough.
HumHub version: 1.14.2

**Comment by Dayflare** [comment]
to add to this, after the daily cron ran the 2 removed posts were removed from the dashboard widget.

**Comment by yurabakhtin** [comment]
@luke- @Dayflare Fixed in PR https://github.com/humhub/news/pull/64:
- Draft news are visible on the dashboard widget only if user has a permission to manage them,
- Deleted news are hidden on the dashboard widget completely.

**Comment by luke-** [comment]
@yurabakhtin Thanks

@Dayflare Fixed in News module v1.1.1
