### ISSUE TITLE
draft visible for all users in dashboard

### ISSUE THREAD

**Issue by Dayflare** [humhub/news-issues#6]
After updating Humhub to version 1.15 and the news plugin to version 1.1.7 new drafts are visible for all users in the dashboard. If the user selects the space, in which the draft was created, the draft is invisible like it should be. 
![image](https://github.com/humhub/news-issues/assets/42730126/9a3cc4c4-3c0a-4106-9bbc-485bfed31cb7)

![image](https://github.com/humhub/news-issues/assets/42730126/93d75f1b-4d1b-4eeb-9829-0132897cff64)

It's not visible on the widget, only in stream itself.

Moderators and admins see the draft in the dashboard, the space and in the widget, like intended.

**Comment by yurabakhtin** [comment]
@luke- Fixed in PR https://github.com/humhub/humhub/pull/6674.
